#+TITLE: My literate Emacs Configuration
#+AUTHOR: Marcus
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_INIT_OPTIONS: slideNumber:true
#+REVEAL_THEME: league
#+REVEAL_HIGHLIGHT_CSS: https://unpkg.com/@highlightjs/cdn-assets@11.9.0/styles/nord.css
#+REVEAL_PLUGINS: (highlight)

* Emacs Configuration 
:PROPERTIES:
:CUSTOM_ID: emacs-configuration
:ID:       87291F55-9407-4438-9CE4-67DFC36DACB5
:END:
=WARNING=

This is my personal Emacs configuration. It is a work in progress. The relavant
configuration files are tangled from this Org-document (=C-c C-v t=). I don't
tangle on save or anything like that. This is a work in progress and will never
be done. This is a rabbit hole...

I regulary commit my configuration to github even though it is not working. Yes,
I know, I shouldn't but I do so you have been warned.

*Here be dragons*

If you are looking for insperation, check out these instead:
- [[https://sachachua.com/blog/][Sacha Chua's Living an awesome life]]
- [[https://protesilaos.com/][Protesilaos Stavrou's personal website]]
- [[https://www.spacemacs.org/][Spacemacs - a community-driven Emacs distribution]]
- [[https://github.com/doomemacs/doomemacs][Doom Emacs - a configuration framework for Emacs]]

If you want to learn more about Org:
- [[https://orgmode.org/manual/index.html][The Org manual]]
- [[https://www.gnu.org/software/emacs/tour/][A guided tour of Emacs]]
- [[https://www.gnu.org/software/emacs/manual/index.html][GNU Emacs Manuals Online]]
  
* Table of Contents
:PROPERTIES:
:TOC:      :include all :depth 4 :ignore (this) 
:ID:       C7943AE1-FE55-46C9-AEC1-F28F84970B23
:END:
:CONTENTS:
- [[#emacs-configuration][Emacs Configuration]]
- [[#generate-files-and-file-headers][Generate files and file headers]]
  - [[#initel][init.el]]
  - [[#early-initel][early-init.el]]
  - [[#customel][custom.el]]
  - [[#aliases][Aliases]]
  - [[#profile][Profile]]
- [[#put-stuff-in-early-initel][Put stuff in early-init.el]]
  - [[#garbage-collection][Garbage collection]]
- [[#package-manager][Package Manager]]
- [[#macos-specifics][MacOS Specifics]]
  - [[#exec-path-from-shell][Exec path from shell]]
  - [[#macos-keyboard-settings][MacOS keyboard settings]]
- [[#misc-settings][Misc settings]]
- [[#look-and-feel][Look and Feel]]
  - [[#minibuffer][Minibuffer]]
    - [[#which-key][Which key]]
    - [[#vertico][Vertico]]
    - [[#save-history][Save history]]
    - [[#marginalia][Marginalia]]
    - [[#orderless][Orderless]]
    - [[#emacs-minibuffer-configurations][Emacs minibuffer configurations]]
  - [[#themes-modeline-and-fonts][Themes, modeline and Fonts]]
    - [[#ef-themes][EF-themes]]
    - [[#doom-themes][Doom Themes]]
    - [[#modeline][Modeline]]
    - [[#fonts][Fonts]]
    - [[#where-is-my-cursor][Where is my cursor]]
    - [[#icons][Icons]]
    - [[#windows][Windows]]
- [[#keybindings][Keybindings]]
  - [[#evil][Evil]]
  - [[#my-personal-key-bindings][My personal key bindings]]
  - [[#ivy-and-counsel][IVY and Counsel]]
  - [[#general-key-binding][General key binding]]
  - [[#helpful][Helpful]]
  - [[#move-text][Move text]]
  - [[#tldr][TLDR]]
- [[#programming][Programming]]
  - [[#version-control][Version control]]
    - [[#magit][Magit]]
  - [[#code-completion][Code completion]]
    - [[#corfu][Corfu]]
    - [[#cape][Cape]]
  - [[#project-management][Project management]]
    - [[#projectile][Projectile]]
- [[#org][Org]]
  - [[#org-0][Org]]
  - [[#org-make-toc][Org make-toc]]
  - [[#org-reveal][Org reveal]]
    - [[#htmlize][Htmlize]]
  - [[#org-tempo][Org tempo]]
  - [[#org-bullets][Org bullets]]
- [[#internet][Internet]]
  - [[#browse-url][Browse URL]]
  - [[#elfeed][Elfeed]]
- [[#shells-and-terminals][Shells and terminals]]
  - [[#eshell][Eshell]]
:END:

* Generate files and file headers
:PROPERTIES:
:CUSTOM_ID: generate-files-and-file-headers
:ID:       15430D8A-669B-4FAD-A3A5-E7EF438CFD33
:END:
The file headers sets [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical-binding]] to true. I also try to warn people not to
use this configuration as is.

*Here be dragons*

** init.el
:PROPERTIES:
:CUSTOM_ID: initel
:ID:       C784E801-08CA-4669-8BBD-E79995DA6869
:END:
Header text and [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding]].

#+begin_src emacs-lisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-

;;; Commentary:
;; This is my personal Emacs configuration. The file is tangled from a
;; literate org document where I try to document what each piece is for.
;; If you found my configurations you are free to use as you please, but
;; please read the whole thing before you do. I regulary commit my
;; configuration even though it is not working. Yes, I know, you shouldn't
;; do that but you have been warned.

;; Here be dragons

;; Code:
#+end_src

** early-init.el
:PROPERTIES:
:CUSTOM_ID: early-initel
:ID:       40842719-67BD-4940-B894-61C927D529B3
:END:
Header text and [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding]].

#+begin_src emacs-lisp :tangle early-init.el
;;; early-init.el -*- lexical-binding: t; -*-

;;; Commentary:
;; This is my personal Emacs configuration. The file is tangled from a
;; literate org document where I try to document what each piece is for.
;; If you found my configurations you are free to use as you please, but
;; please read the whole thing before you do. I regulary commit my
;; configuration even though it is not working. Yes, I know, you shouldn't
;; do that but you have been warned.

;; Here be dragons

;; Code:
#+end_src

** custom.el
:PROPERTIES:
:CUSTOM_ID: customel
:ID:       C8237143-D3B4-4A1F-AD20-F1B6A0B9324D
:END:
In Emacs, a custom file is used to store customization settings seperately
from the main init file, allowing for easier management of user preferences.
I use this literate org-file but I like to separate the preferences all the same.

#+begin_src emacs-lisp :tangle init.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

** Aliases
:PROPERTIES:
:CUSTOM_ID: aliases
:ID:       F5DE7D60-F62C-4EE4-91FF-F3A22DD8AD2B
:END:
#+begin_src bash :tangle eshell/aliases
  # alias for emacs commands
  alias ff find-file $1

  # aliasing standard shell commands to better emacs alternatives
  alias less view-file $1

  # using exa instead of ls
  alias ls eza -al --color=always --group-directories-first $*   # my prefered listing
  alias la eza -a --color=always --group-directories-first $*    # all files and directories
  alias ll eza -l --color=always --group-directories-first $*    # long format
  alias lt eza -aT --color=always --group-directories-first $*   # tree listing
  alias l. eza -a1 $* | grep "^\."                               # list hidden files
#+end_src

** Profile
:PROPERTIES:
:CUSTOM_ID: profile
:ID:       83FC4DED-47A6-40B8-BEE4-95AFCBAC73FF
:END:
#+begin_src bash :tangle eshell/profiles
  # I had a thought what to put in here but it eluded me
#+end_src

* Put stuff in early-init.el
:PROPERTIES:
:ID:       F46F08A4-309D-47DA-B246-23E70D9B935D
:CUSTOM_ID: put-stuff-in-early-initel
:END:
** Garbage collection
:PROPERTIES:
:ID:       6E4C54B3-EEB2-4F4D-B34F-FCDFD1D0C789
:CUSTOM_ID: garbage-collection
:END:
#+begin_src emacs-lisp :tangle early-init.el
  (setq gc-cons-theshold 64000000)
  (add-hook 'after-init-hook #'(lambda () (setq gc-cons-threshold 800000)))
#+end_src

* Package Manager
:PROPERTIES:
:CUSTOM_ID: package-manager
:ID:       57431B1C-2313-47DC-85FD-E5787A494314
:END:
[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html][Package installation]] are usually installed using =use-package=. Some packages
are downloaded or cloned from sources outside of the ones listed below. These
packages live in =~/.emacs.d/manual-packages=. This code sets up the package
manager, adds sources and initialize the packages manager.

#+begin_src emacs-lisp :tangle init.el
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
  			 ("melpa-stable" . "https://stable.melpa.org/packages/")
  			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
  			 ("gnu" . "https://elpa.gnu.org/packages/")))
  (setq package-user-dir (expand-file-name "~/.emacs.d/packages"))
  (require 'package)
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install-selected-packages)
  (require 'use-package)
#+end_src

#+RESULTS:
: use-package

* MacOS Specifics
:PROPERTIES:
:CUSTOM_ID: macos-specifics
:ID:       B61BF246-5E1F-4AAE-9CB3-1CC59670A49E
:END:
I use a MacBook (arm) for my main laptop. I *try* to keep all the MacOS stuff
behind =when= so I can use this configuration on my Linux machines as well.

** Exec path from shell
:PROPERTIES:
:CUSTOM_ID: exec-path-from-shell
:ID:       73F551DD-200B-4DF2-AD3C-4C01903A44E4
:END:
A GNU Emacs library to ensure environment variables inside Emacs look the same
as in the user's shell.

#+begin_src emacs-lisp :tangle init.el
(when (memq window-system '(mac ns))
  (use-package exec-path-from-shell
  :ensure t
  :config
  (exec-path-from-shell-initialize)))
#+end_src

** MacOS keyboard settings
:PROPERTIES:
:CUSTOM_ID: macos-keyboard-settings
:ID:       AD2CB2D1-9217-43A0-A0D2-555B72F4C5C9
:END:
My prefered keyboard settings when on a Mac.

#+begin_src emacs-lisp :tangle init.el
  (when (eq system-type 'darwin)
    (setq mac-option-modifier 'meta
          mac-command-modifier 'super
          mac-right-option-modifier 'none)
    (global-set-key (kbd "s-c") 'kill-ring-save)
    (global-set-key (kbd "s-v") 'yank)
    (global-set-key (kbd "s-x") 'kill-region)
    (global-set-key (kbd "s-a") 'mark-whole-buffer)
    (global-set-key (kbd "s-z") 'undo)
    (global-set-key (kbd "s-f") 'isearch-forward)
    (global-set-key (kbd "s-g") 'isearch-repeat-forward)
    (global-set-key (kbd "s-o") 'find-file)
    (global-set-key (kbd "s-n") 'find-file)
    (global-set-key (kbd "s-s") 'save-buffer)
    ;(global-set-key (kbd "s-p") 'mac-preview)
    (global-set-key (kbd "s-w") 'kill-buffer)
    (global-set-key (kbd "s-m") 'iconify-frame)
    (global-set-key (kbd "s-q") 'save-buffers-kill-emacs)
    (global-set-key (kbd "s-.") 'keyboard-quit)
    (global-set-key (kbd "s-l") 'goto-line)
    (global-set-key (kbd "s-k") 'kill-buffer)
    (global-set-key (kbd "s-<up>") 'beginning-of-buffer)
    (global-set-key (kbd "s-<down>") 'end-of-buffer)
    (global-set-key (kbd "s-<left>") 'beginning-of-line)
    (global-set-key (kbd "s-<right>") 'end-of-line)
    (global-set-key [(meta down)] 'forward-paragraph)
    (global-set-key [(meta up)] 'backward-paragraph)
    )
#+end_src
* Misc settings
:PROPERTIES:
:CUSTOM_ID: misc-settings
:ID:       0836D54C-E325-4709-84E3-692BB7F718EE
:END:
Settings that doesn't fit in anywhere else.

#+begin_src emacs-lisp :tangle init.el
  (setq-default c-basic-offset 4 ; Amount of basic offset used by + and - symbols in 'c-offsets-alist'. 
  	      c-default-style "linux" ; Style which gets installed by default when a file is visited.
  	      indent-tabs-mode nil ; Don't insert tabs
  	      fill-column 80 ; Column beyond which automatic line-wrapping should happen.
            column-number-mode t ; Show column number in modeline.
  	      tab-width 4) ; Distance between tab stops, in columns.

  (tool-bar-mode -1) ; Disable the tool-bar.
  (scroll-bar-mode -1) ; Specify whether to have vertical scroll bars, and on which side.
  (menu-bar-mode t) ; I use a Mac and it looks odd if there is no menu

  (setq load-prefer-newer t) ; Non-nil means load prefers the newest version of a file.
  (setq tab-always-indent 'complete) ; Controls the operation of the TAB key.

  (delete-selection-mode 1) ; select text and delete it by typing.
  (setq org-support-shift-select t) ; Non-nil means make shift-cursor select text when possible.

  (global-hl-line-mode 1) ; Highlight the current line in Emacs.

  (setq display-line-numbers 'relative) ; Show relative line numbers
#+end_src
* Look and Feel
:PROPERTIES:
:CUSTOM_ID: look-and-feel
:ID:       74E7C440-49F1-4C6A-B8E7-D0F706B9FCCC
:END:
** Minibuffer
:PROPERTIES:
:CUSTOM_ID: minibuffer
:ID:       E53B959F-383A-4358-830D-775ED30F6878
:END:
*** Which key
:PROPERTIES:
:CUSTOM_ID: which-key
:ID:       8426C530-0A1E-4EE2-BEF4-51867EAF7B59
:END:
[[https://github.com/justbur/emacs-which-key][which-key]] is a minor mode for Emacs that displays the key bindings following your currently entered incomplete
command (a prefix) in a popup. 

#+begin_src emacs-lisp :tangle init.el
  (use-package which-key
    :ensure t
    :delight
    :custom (which-key-idle-delay 0.5)
    :config (which-key-mode))
#+end_src
*** Vertico
:PROPERTIES:
:CUSTOM_ID: vertico
:ID:       2FB254F4-A6DB-4450-8923-CABD6D949E48
:END:
[[https://github.com/minad/vertico][Vertico]] provides a performant and minimalistic vertical completion UI based on the default completion system. 

#+begin_src emacs-lisp :tangle init.el
    (use-package vertico
      :ensure t
      :init (vertico-mode)
      :bind (:map vertico-map
    	      ("C-<backspace>" . vertico-directory-up))
      :config
      (keymap-set vertico-map "?" #'minibuffer-completion-help)
      (keymap-set vertico-map "M-RET" #'minibuffer-force-complete-and-exit)
      (keymap-set vertico-map "M-TAB" #'minibuffer-complete))
#+end_src
*** Save history
:PROPERTIES:
:CUSTOM_ID: save-history
:ID:       32FA4BA0-A438-402A-8984-E739CEA64453
:END:
Vertico sorts by history position.

#+begin_src emacs-lisp :tangle init.el
  (use-package savehist
    :init
    (savehist-mode))
#+end_src
*** Marginalia
:PROPERTIES:
:CUSTOM_ID: marginalia
:ID:       2BC7F539-41DA-4BD5-91A3-A5C31559404B
:END:
[[https://github.com/minad/marginalia][Marginalia]] are marks or annotations placed at the margin of the page of a book or in this case helpful colorful
annotations placed at the margin of the minibuffer for your completion candidates.

#+begin_src emacs-lisp :tangle init.el
  (use-package marginalia
    :ensure t
    :after vertico
    :init (marginalia-mode)
    :custom
    (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil)))
#+end_src
*** Orderless
:PROPERTIES:
:CUSTOM_ID: orderless
:ID:       63F6F48E-4EBB-46A6-9AE1-0E2E0DC37653
:END:
This package provides an [[https://github.com/oantolin/orderless][orderless]] completion style that divides the pattern into space-separated components,
and matches candidates that match all of the components in any order. Each component can match in any one of several
ways: literally, as a regexp, as an initialism, in the flex style, or as multiple word prefixes. By default, regexp
and literal matches are enabled.

#+begin_src emacs-lisp :tangle init.el
  (use-package orderless
    :ensure t
    :custom
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles . (partial-completion)))))
    (completion-styles '(orderless basic)))
#+end_src
*** Emacs minibuffer configurations
:PROPERTIES:
:CUSTOM_ID: emacs-minibuffer-configurations
:ID:       71A0D34E-5259-4249-838C-FF3004A53793
:END:

#+begin_src emacs-lisp :tangle init.el
  (use-package emacs
    :custom
    (enable-recursive-minibuffers t)
    (read-extended-command-predicate #'command-completion-default-include-p)
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src
** Themes, modeline and Fonts
:PROPERTIES:
:CUSTOM_ID: themes-modeline-and-fonts
:ID:       339241CE-AE87-471A-9E22-D5CBA0ADBADA
:END:
Some packages, such as EF-themes, I download myself into =~/.emacs.d/manual-packages/<package>=.
To be able to use these packages I first add the path to the =load-path= list and then =require=
each package.

My default theme is =ef-elea-light= and =ef-elea-dark=.
I can switch between these themes using =M-x ef-themes-toggle= or with keybinding =X=.

*** EF-themes
:PROPERTIES:
:CUSTOM_ID: ef-themes
:ID:       DFFB7E31-6684-412F-9BDF-9C7829EBCEE5
:END:
The [[https://github.com/protesilaos/ef-themes][ef-themes]] are a collection of light and dark themes for GNU Emacs whose
goal is to provide colorful ("pretty") yet legible options for users who want
something with a bit more flair than the [[https://github.com/protesilaos/modus-themes][modus-themes]].

#+begin_src emacs-lisp :tangle init.el
      (add-to-list 'load-path "~/.emacs.d/manual-packages/ef-themes")
      (require 'ef-themes)
      (setq ef-themes-to-toggle '(ef-arbutus ef-elea-dark))
      (setq ef-themes-headings
      	'((0 variable-pitch light 1.9)
      	  (1 variable-pitch light 1.8)
      	  (2 variable-pitch regular 1.7)
      	  (3 variable-pitch regular 1.6)
      	  (4 variable-pitch regular 1.5)
      	  (5 variable-pitch 1.4) ; absence of weight means 'bold'
      	  (6 variable-pitch 1.3)
      	  (7 variable-pitch 1.2)
      	  (t variable-pitch 1.1)))
    (setq ef-themes-mixed-fonts t
          ef-themes-variable-pitch-ui t)
  (mapc #'disable-theme custom-enabled-themes) ; disable all other themes to avoid awkward blending
  (load-theme 'ef-arbutus :no-confirm)
#+end_src
*** Doom Themes
:PROPERTIES:
:CUSTOM_ID: doom-themes
:ID:       6D247877-927E-4B1F-85BF-D38000573E64
:END:
A [[https://github.com/doomemacs/themes][theme megapack]] for GNU Emacs, inspired by community favorites.

#+begin_src emacs-lisp :tangle init.el
  (use-package doom-themes
    :ensure t)
#+end_src

*** Modeline
:PROPERTIES:
:CUSTOM_ID: modeline
:ID:       F4974265-8360-4042-8229-622A69400DE9
:END:
[[https://github.com/seagle0128/doom-modeline][Doom modeline]] is used to cleanup and configure the modeline.

#+begin_src emacs-lisp :tangle init.el
  (use-package doom-modeline
    :ensure t
    :config
    (setq
     doom-modeline-support-imenu t
     doom-modeline-icon t
     doom-modeline-major-mode-icon t
     doom-modeline-buffer-state-icon t
     doom-modeline-buffer-modification-icon t
     doom-modeline-column-zero-based t
     doom-modeline-highlight-modified-buffer-name nil
     doom-modeline-percent-position '(-3 "%p")
     doom-modeline-position-column-line-format '("%l:%c")
     doom-modeline-total-line-number t
     doom-modeline-modal t
     doom-modeline-modal-modern-icon t
     doom-modeline-time t
     )
    (setq doom-modeline-height 25)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil :family "Noto Sans" :height 140)
      (set-face-attribute 'mode-line nil :family "Noto Sans" :height 140)
      (set-face-attribute 'mode-line-inactive nil :family "Noto Sans" :height 140))
    :init
    (doom-modeline-mode 1))
#+end_src

*** Fonts
:PROPERTIES:
:CUSTOM_ID: fonts
:ID:       61D8C5B1-D4AE-4034-92A6-6F26C1728114
:END:
Setting the font faces.
#+begin_src emacs-lisp :tangle init.el
  (set-face-attribute 'default nil
                      :font "Iosevka Fixed"
                      :height 160
                      :weight 'medium)
  (set-face-attribute 'variable-pitch nil
                      :font "Iosevka"
                      :height 150
                      :weight 'medium)
  (set-face-attribute 'fixed-pitch nil
                      :font "Iosevka Fixed"
                      :height 170
                      :weight 'medium)
  (set-face-attribute 'font-lock-comment-face nil
                      :slant 'italic)
  (set-face-attribute 'font-lock-keyword-face nil
                      :slant 'italic)
#+end_src

*** Where is my cursor
:PROPERTIES:
:CUSTOM_ID: where-is-my-cursor
:ID:       B0A198EA-4662-4C5E-BE4B-80FC2B8F5291
:END:
**** Beacon
:PROPERTIES:
:ID:       4004A920-C15D-4ED6-A047-C7E467DA0D53
:END:
[[https://github.com/Malabarba/beacon][Beacon]] is a light that follows your cursor around so you don't lose it. Currently not used in
my config. To enable it add =:tangle init.el= in the source code block.
#+begin_src emacs-lisp  
  (use-package beacon
    :ensure t
    :config
    (setq beacon-blink-duration 0.5
          beacon-blink-when-window-scrolls t
          beacon-blink-when-window-changes t
          beacon-blink-when-point-moves t)
    :init
    (beacon-mode 1))
#+end_src
**** Pulsar
:PROPERTIES:
:ID:       92700793-A40B-4D12-ADC8-D7CBC7D11D4C
:END:
[[https://github.com/protesilaos/pulsar][Pulsar]] is an Emacs package that pulse the current line after running select functions.
#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'load-path "~/.emacs.d/manual-packages/pulsar")
  (require 'pulsar)
  (setq pulsar-pulse t
        pulsar-delay 0.055
        pulsar-iterations 15
        pulsar-face 'pulsar-magenta
        pulsar-highlight-face 'pulsar-yellow
        )
  (let ((map global-map))
    (define-key map (kbd "C-c h p") #'pulsar-pulse-line)
    (define-key map (kbd "C-c h h") #'pulsar-highlight-line))
  (pulsar-global-mode 1)
#+end_src
*** Icons
:PROPERTIES:
:CUSTOM_ID: icons
:ID:       FDD7A7C7-33EA-4289-BFB0-22FE7CDA6C77
:END:
**** All-the-icons
:PROPERTIES:
:ID:       9606C0D9-5601-423F-8AC6-50BF7397AFBA
:END:
[[https://github.com/domtronn/all-the-icons.el][All-the-icons]] is a utility package to collect various Icon Fonts and propertize them within Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package all-the-icons
    :ensure t
    :if (display-graphic-p))
#+end_src
**** All-the-icons-completion
:PROPERTIES:
:ID:       B07244C7-32BE-452D-B637-8289F257F72B
:END:
[[https://github.com/iyefrat/all-the-icons-completion][All-the-icons-completion]] adds icons to completion candidates in Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package all-the-icons-completion
    :ensure t
    :defer
    :hook (marginalia-mode . #'all-the-icons-completion-marginalia-setup)
    :init
    (all-the-icons-completion-mode))
#+end_src
**** Nerd icons
:PROPERTIES:
:ID:       0D81B940-D772-49D4-984A-4A71C28D3770
:END:
[[https://github.com/emacsmirror/nerd-icons][Nerd-icons]] - Emacs Nerd Font Icons Library.

#+begin_src emacs-lisp :tangle init.el
  (use-package nerd-icons
    :ensure t)
#+end_src
*** Windows
:PROPERTIES:
:CUSTOM_ID: windows
:ID:       76990538-E1FE-4D1F-A94F-B6A5F594140A
:END:
**** Window
:PROPERTIES:
:ID:       E4922E07-5BB7-4920-88AF-427DFC123E4F
:END:
Setup how to split windows in Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package window
    :ensure nil
    :bind (("C-x 2" . vsplit-last-buffer)
           ("C-x 3" . hsplit-last-buffer)
           ([remap kill-buffer] . kill-this-buffer))
    :preface
    (defun hsplit-last-buffer ()
      "Focus to the last created horizontal window."
      (interactive)
      (split-window-horizontally)
      (other-window 1))
    (defun vsplit-last-buffer ()
      "Focus to the last created vertical window."
      (interactive)
      (split-window-vertically)
      (other-window 1)))
#+end_src
**** Switch window
:PROPERTIES:
:ID:       8634A72C-DFC0-4DD6-AE13-91BC22A9B66B
:END:
[[https://github.com/dimitri/switch-window][Switch-window]] offer a visual way to choose a window to switch to.

#+begin_src emacs-lisp :tangle init.el
  (use-package switch-window
    :ensure t
    :bind (("C-x o" . switch-window)
           ("C-x w" . switch-window-then-swap-buffer)))
#+end_src
**** Winner
:PROPERTIES:
:ID:       D61E84D9-1733-483C-B0AA-28E3E2645D24
:END:
Winner mode in Emacs allows you to restore previous window configurations after
they have been changed, making it easier to manage your layout.

#+begin_src emacs-lisp :tangle init.el
  (use-package winner
    :ensure nil
    :config (winner-mode))
#+end_src
**** Ibuffer
:PROPERTIES:
:ID:       6C09128F-D990-4CBB-AD15-EBB93ED8E310
:END:
I found a post [[https://tech.tonyballantyne.com/2020/09/26/ibuffer-changed-my-life/][ibuffer changed my life]] from Tony Ballantyne Tech.

#+begin_src emacs-lisp :tangle init.el
  (global-set-key (kbd "C-x C-b") 'ibuffer) ; instead of buffer-list
  (setq ibuffer-expert t)                   ; stop yes no prompt on delete
  (setq ibuffer-saved-filter-groups
        (quote (("default"
                 ("dired" (mode . dired-mode))
                 ("org" (mode . org-mode))
                 ("magit" (name . "^magit"))
                 ("planner" (or
                             (name . "^\\*Calendar\\*$")
                             (name . "^\\*Org Agenda\\*$")))
                 ("emacs" (or
                           (name . "^\\*scratch\\*$")
                           (name . "^\\*Messages\\*$")))
                 ))))
  (add-hook 'ibuffer-mode-hook (lambda ()
                                 (ibuffer-switch-to-saved-filter-groups "default")))
#+end_src
**** Dashboard
:PROPERTIES:
:ID:       FD102CAC-728C-4EC9-9126-264619072CE5
:END:
[[https://github.com/emacs-dashboard/emacs-dashboard][Dashboard]] is an extensible emacs startup screen showing you what’s most important.

#+begin_src emacs-lisp :tangle init.el
  (use-package dashboard
    :ensure t
    :config
    (setq dashboard-banner-logo-text "Emacs, what else?"
          dashboard-startup-banner 'official
          dashboard-center-content t
          dashboard-vertically-center-content t
          dashboard-show-shortcuts t)
    (setq dashboard-items '((recents . 10)
                            (bookmarks . 10)
                            (projects . 10)
                            (agenda . 10)
                            (registers . 10)))
    (setq dashboard-item-shortcuts '((recents . "r")
                                     (bookmarks . "b")
                                     (projects . "p")
                                     (agenda . "a")
                                     (registers . "e")))
    (setq dashboard-navigation-cycle t
          dashboard-display-icons-p t)
     :init
    (dashboard-setup-startup-hook))
#+end_src
* Keybindings
:PROPERTIES:
:CUSTOM_ID: keybindings
:ID:       CAC3197F-094A-4657-8CC8-5B86175271C3
:END:
*** Evil
:PROPERTIES:
:CUSTOM_ID: evil
:ID:       80611870-A047-4A1E-9BC4-4D4DDBFF39F9
:END:
[[https://github.com/emacs-evil/evil][Evil]] is an extensible *vi* layer for Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)
    (evil-mode 1))
  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (add-to-list 'evil-collection-mode-list 'help)
    (evil-collection-init))
  (with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd "SPC") nil)
    (define-key evil-motion-state-map (kbd "RET") nil)
    (define-key evil-motion-state-map (kbd "TAB") nil))
  (setq org-return-follows-link t)
#+end_src
*** My personal key bindings
:PROPERTIES:
:CUSTOM_ID: my-personal-key-bindings
:ID:       BA6DEAEB-9E41-41C9-BEB1-0CB34B15E9D7
:END:
I will try to enter all my personal key bindings here... but some are defined
in the MacOS keyboard settings and some are defined in other places. And there
are a lot of them in the =General= section below. Oh my.

#+begin_src emacs-lisp :tangle init.el
  (global-set-key (kbd "C-c t") 'ef-themes-toggle)       ; toggle theme 
  (global-set-key (kbd "C-c g") 'magit-status)           ; magit status
  (global-set-key (kbd "C-c p") 'projectile-command-map) ; projectile command map
  (global-set-key (kbd "C-+") 'text-scale-increase)      ; increase text size
  (global-set-key (kbd "C--") 'text-scale-decrease)      ; decrease text size
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
  (global-set-key [escape] 'keyboard-escape-quit)        ; be default, Emacs requires you to hit ESC
                                                         ; three times to escape quit the minibuffer
#+end_src
*** IVY and Counsel
:PROPERTIES:
:CUSTOM_ID: ivy-and-counsel
:ID:       E418697D-1872-4BEB-B20A-962B42F57CA1
:END:
#+begin_src emacs-lisp :tangle init.el
  (use-package counsel
    :ensure t
    :after ivy
    :diminish
    :config
    (counsel-mode)
    (setq ivy-initial-inputs-alist nil))

  (use-package ivy
    :ensure t
    :bind
    (("C-c C-r" . ivy-resume)
     ("C-x B" . ivy-switch-buffer-other-window))
    :diminish
    :custom
    (setq ivy-use-virtual-buffers t
          ivy-count-format "(%d/%d) "
          enable-recursive-minibuffers t)
    :config
    (ivy-mode))

  (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))

  (use-package ivy-rich
    :ensure t
    :after ivy
    :init (ivy-rich-mode 1)
    :custom (ivy-virtual-abbreviate 'full
                                    ivy-rich-switch-buffer-align-virtual-buffer t
                                    ivy-rich-path-style 'abbrev)
    :config
    (ivy-set-display-transformer 'ivy-switch-buffer
                                 'ivy-rich-switch-buffer-transformer))
#+end_src
*** General key binding
:PROPERTIES:
:CUSTOM_ID: general-key-binding
:ID:       8C1D41DB-BC1B-4541-864B-625961940AD9
:END:
[[https://github.com/noctuid/general.el][General]] is a more convenient key definition system in Emacs.
#+begin_src emacs-lisp :tangle init.el
  (use-package general
    :ensure t
    :config
    (general-evil-setup)
    ;; set up "SPC" as the global leader key
    (general-create-definer my/leader-keys
                            :states '(normal insert visual emacs)
                            :keymaps 'override
                            :prefix "SPC"
                            :global-prefix "M-SPC") ; access leader key in insert mode
    (my/leader-keys
     "SPC" '(counsel-M-x :wk "Counsel M-x")
     "." '(find-file :wk "Find file")
     "TAB TAB" '(comment-line :wk "Comment lines")
     "u" '(universal-argument :wk "Universal argument")
     )

    (my/leader-keys
      "b" '(:ignore t :wk "Bookmarks/Buffers")
      "b b" '(switch-to-buffer :wk "Switch to buffer")
      "b c" '(clone-indirect-buffer :wk "Create indirect buffer copy in a split")
      "b C" '(clone-indirect-buffer-other-window :wk "Clone indirect buffer in new window")
      "b d" '(bookmark-delete :wk "Delete bookmark")
      "b i" '(ibuffer :wk "Ibuffer")
      "b k" '(kill-current-buffer :wk "Kill current buffer")
      "b l" '(list-bookmarks :wk "List bookmarks")
      "b m" '(bookmark-set :wk "Set bookmark")
      "b n" '(next-buffer :wk "Next buffer")
      "b p" '(previous-buffer :wk "Previous buffer")
      "b r" '(revert-buffer :wk "Reload buffer")
      "b R" '(rename-buffer :wk "Rename buffer")
      "b s" '(basic-save-buffer :wk "Save buffer")
      "b S" '(save-some-buffers :wk "Save multiple buffers")
      "b w" '(bookmark-save :wk "Save current bookmarks to bookmark file")
      )

    (my/leader-keys
      "d" '(:ignore t :wk "Dired")
      "d d" '(dired :wk "Open dired")
      "d j" '(dired-jump :wk "Dired jump to current")
      )

    (my/leader-keys
      "e" '(:ignore t :wk "Eshell/Evaluate")
      "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
      "e d" '(eval-defun :wk "Evaluate defun containing or after point")
      "e e" '(eval-expression :wk "Evaluate and elisp expression")
      "e h" '(counsel-ssh-history :wk "Eshell history")
      "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
      "e r" '(eval-region :wk "Evaluate elisp in region")
      "e R" '(eww-reload :wk "Reload current page in EWW")
      "e s" '(eshell :wk "Eshell")
      "e w" '(eww :wk "EWW emacs web browser")
      )

    (my/leader-keys
      "f" '(:ignore t :wk "Files")
      "f c" '((lambda () (interactive) (find-file "~/.emacs.d/README.org")) :wk "Open emacs configuration file")
      "f e" '((lambda () (interactive) (dired "~/.emacs.d/")) :wk "Open user-emacs-directory in dired")
      "f g" '(counsel-grep-or-swiper :wk "Search for string current file")
      "f j" '(counsel-file-jump :wk "Jump to a file below current directory")
      "f l" '(counsel-locate :wk "Locate a file")
      "f r" '(counsel-recentf :wk "Find recent files")
      )

    (my/leader-keys
      "g" '(:ignore t :wk "Git")
      "g d" '(magit-dispatch :wk "Magit dispatch")
      "g ." '(magit-file-dispatch :wk "Magit file dispatch")
      "g b" '(magit-branch-checkout :wk "Switch branch")
      "g c" '(:ignore t :wk "Create")
      "g c b" '(magit-branch-and-checkout :wk "Create branch and checkout")
      "g c c" '(magit-commit-create :wk "Create commit")
      "g c f" '(magit-commit-fixup :wk "Create fixup commit")
      "g C" '(magit-clone :wk "Clone repo")
      "g f" '(:ignore t :wk "Find")
      "g f c" '(magit-show-commit :wk "Magit show commit")
      "g f f" '(magit-find-file :wk "Magit find file")
      "g f g" '(magit-find-git-config-file :wk "Find gitconfig file")
      "g F" '(magit-fetch :wk "Git fetch")
      "g g" '(magit-status :wk "Magit status")
      "g i" '(magit-init :wk "Initialize git repo")
      "g l" '(magit-log-buffer-file :wk "Magit buffer log")
      "g r" '(vc-revert :wk "Git revert file")
      "g s" '(magit-stage-file :wk "Git stage file")
      "g u" '(magit-unstage-file :wk "Git unstage file")
      )

    (my/leader-keys
      "h" '(:ignore t :wk "Help")
      "h a" '(counsel-apropos :wk "Apropos")
      "h b" '(describe-bindings :wk "Desc. bindings")
      "h c" '(describe-char :wk "Desc. character under cursor")
      "h d" '(:ignore t :wk "Emacs documentation")
      "h d a" '(about-emacs :wk "About Emacs")
      "h d d" '(view-emacs-debugging :wk "View Emacs debugging")
      "h d f" '(view-emacs-FAQ :wk "View Emacs FAQ")
      "h d m" '(info-emacs-manual :wk "The Emacs manual")
      "h d n" '(view-emacs-news :wk "View Emacs News")
      "h d o" '(describe-distribution :wk "How to obtain Emacs")
      "h d p" '(view-emacs-problems :wk "View Emacs problems")
      "h d t" '(view-emacs-todo :wk "View Emacs todo")
      "h d w" '(describe-no-warranty :wk "Desc. no warranty")
      "h e" '(view-echo-area-messages :wk "View echo area messages")
      "h f" '(describe-function :wk "Desc. function")
      "h F" '(describe-face :wk "Desc. face")
      "h g" '(describe-gnu-project :wk "Desc. GNU Project")
      "h i" '(info :wk "Info")
      "h I" '(describe-input-method :wk "Desc. input method")
      "h k" '(describe-key :wk "Desc. key")
      "h l" '(view-lossage :wk "Display recent keystrokes and the commands run")
      "h L" '(describe-language-environment :wk "Desc. language environment")
      "h m" '(describe-mode :wk "Desc. mode")
      "h r" '(:ignore t :wk "Reload")
      "h r r" '((lambda () (interactive) (load-file "~/.emacs.d/init.el")) :wk "Reload emacs config")
      "h t" '(load-theme :wk "Load theme")
      "h v" '(describe-variable :wk "Desc. variable")
      "h w" '(where-is :wk "Prints keybinding for command if set")
      "h x" '(describe-command :wk "Desc. command")
      )

    (my/leader-keys
      "m" '(:ignore t :wk "Org")
      "m a" '(org-agenda :wk "Org agenda")
      "m e" '(org-export-dispatch :wk "Org export dispatch")
      "m i" '(org-toggle-item :wk "Org toggle item")
      "m t" '(org-todo :wk "Org todo")
      "m B" '(org-babel-tangle :wk "Org babel tangle")
      "m T" '(org-todo-list :wk "Org todo list")
      "m b" '(:ignore t :wk "Tables")
      "m b -" '(org-table-insert-hline :wk "Insert hline in table")
      "m d" '(:ignore t :wk "Date/deadline")
      "m d t" '(org-time-stamp :wk "Org time stamp")
      "m p" '(org-present :wk "Org present")
      )
    

    (my/leader-keys
      "o" '(:ignore t :wk "Open")
      "o d" '(dashboard-open :wk "Dashboard")
      "o e" '(elfeed :wk "Open Elfeed")
      "o u" '(elfeed-update :wk "Elfeed update")
      )

    (my/leader-keys
      "p" '(projectile-command-map :wk "Projectile")
      )

    (my/leader-keys
      "s" '(:ignore t :wk "Search")
      "s d" '(dictionary-search :wk "Search dictioinary")
      "s m" '(man :wk "Man pages")
      "s t" '(tldr :wk "Lookup TLDR docs for a command")
      )

    (my/leader-keys
      "t" '(:ignore t :wk "Toggle")
      "t t" '(ef-themes-toggle :wk "Switch light/dark theme")
      "t e" '(eshell-toggle :wk "Toggle Eshell")
      "t l" '(display-line-numbers-mode :wk "Toggle line numbers")
      "t r" '((lambda() (interactive) (setq display-line-numbers 'relative)) :wk "Relative line numbers")
      "t o" '((lambda() (interactive) (setq display-line-numbers 't)) :wk "Ordinary line numbers")
      )

    (my/leader-keys
      "w" '(:ignore t :wk "Windows")
      "w c" '(evil-window-delete :wk "Close window")
      "w n" '(evil-window-new :wk "New window")
      "w s" '(evil-window-split :wk "Horizontal split window")
      "w v" '(evil-window-vsplit :wk "Vertical split window")
      "w h" '(evil-window-left :wk "Window left")
      "w j" '(evil-window-down :wk "Window down")
      "w l" '(evil-window-right :wk "Window right")
      "w k" '(evil-window-up :wk "Window up")
      "w w" '(evil-window-next :wk "Next window")
      )
    
    ) 
#+end_src
*** Helpful
:PROPERTIES:
:CUSTOM_ID: helpful
:ID:       077B8588-874C-47A3-8EDB-56877C71DA60
:END:
[[https://github.com/Wilfred/helpful][Helpful]] is an alternative to the built-in Emacs help that provides much more contextual information.


#+begin_src emacs-lisp :tangle init.el
  (use-package helpful
    :ensure t
    :commands (helpful-at-point
  	     helpful-callable
  	     helpful-command
  	     helpful-function
  	     helpful-key
  	     helpful-macro
  	     helpful-variable)
    :bind
    ([remap display-local-help] . helpful-at-point)
    ([remap describe-function] . helpful-callable)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-symbol] . helpful-symbol)
    ([remap describe-key] . helpful-key)
    ([remap describe-command] . helpful-command))
#+end_src
*** Move text
:PROPERTIES:
:CUSTOM_ID: move-text
:ID:       5BD7A0C2-8D6D-4974-BCDC-10B4C29BE203
:END:
[[https://github.com/emacsfodder/move-text][MoveText]] allows you to move the current line using M-up / M-down (or any other bindings you choose)
if a region is marked, it will move the region instead.

#+begin_src emacs-lisp :tangle init.el
  (use-package move-text
    :ensure t
    :defer
    :init (move-text-default-bindings))
#+end_src
*** TLDR
:PROPERTIES:
:CUSTOM_ID: tldr
:ID:       49ABCA44-9D3B-4933-A53D-BC3697EA8CC3
:END:
#+begin_src emacs-lisp :tangle init.el
  (use-package tldr
    :ensure t)
#+end_src
* Programming
:PROPERTIES:
:CUSTOM_ID: programming
:ID:       6B683060-B2A3-47FF-8FC2-F87351A4BD0F
:END:
** Version control
:PROPERTIES:
:CUSTOM_ID: version-control
:ID:       50CCEE1D-FA4D-47D0-BF75-7577CE8F4662
:END:
*** Magit
:PROPERTIES:
:CUSTOM_ID: magit
:ID:       FD662F5E-B9FA-4C4A-BB4B-A4001A401DCA
:END:
[[https://magit.vc/][Magit]] is a complete text-based user interface to Git. It fills the glaring gap between
the Git command-line interface and various GUIs, letting you perform trivial as well as
elaborate version control tasks with just a couple of mnemonic key presses. Magit looks
like a prettified version of what you get after running a few Git commands but in Magit
every bit of visible information is also actionable to an extent that goes far beyond
what any Git GUI provides and it takes care of automatically refreshing this output when
it becomes outdated. In the background Magit just runs Git commands and if you wish you
can see what exactly is being run, making it possible for you to learn the git command-line
by using Magit.

#+begin_src emacs-lisp :tangle init.el
  (use-package magit
    :ensure t)
#+end_src
** Code completion
:PROPERTIES:
:ID:       67EE4C12-C335-4C7F-A3E5-A934150B999D
:CUSTOM_ID: code-completion
:END:
*** Corfu
:PROPERTIES:
:ID:       0D468204-32B8-41BB-B29B-8DDD2F9A6FD2
:CUSTOM_ID: corfu
:END:
[[https://github.com/minad/corfu][Corfu]] enhances in-buffer completion with a small completion popup.

#+begin_src emacs-lisp :tangle init.el
  (use-package corfu
    :ensure t
    :defer t
    :init (global-corfu-mode))
  (use-package emacs
    :custom
    (tab-always-indent 'complete)
    (text-mode-ispell-word-completion nil)
    (read-extended-command-predicate #'command-completion-default-include-p))
  (use-package dabbrev
    :ensure t
    :bind (("M-/" . dabbrev-completion)
           ("C-M-/" . dabbrev-expand))
    :config
    (add-to-list 'dabbrev-ignored-buffer-regexps "\\` ")
    (add-to-list 'dabbrev-ignored-buffer-modes 'doc-view-mode)
    (add-to-list 'dabbrev-ignored-buffer-modes 'pdf-view-mode)
    (add-to-list 'dabbrev-ignored-buffer-modes 'tags-table-mode))
#+end_src
#+begin_src emacs-lisp
;;; This setting makes M-x useless for some reason
  (use-package corfu
      :ensure t
      :defer t
      :commands (corfu-mode global-corfu-mode)
      :hook ((prog-mode . corfu-mode)
             (shell-mode .corfu-mode)
             (eshell-mode . corfu-mode))
      :custom
      (read-extended-command-predicate #'command-completion-default-include p)
      (text-mode-ispell-word-completion nil)
      (tab-always-indent 'complete)
      :config
      (global-corfu-mode))
#+end_src
*** Cape
:PROPERTIES:
:ID:       FEC3E5EA-ABBF-44DD-9526-10CFE0AB9ABC
:CUSTOM_ID: cape
:END:
[[https://github.com/minad/cape][Cape]] provides completion at point extensions which can be used in comlbination with
[[https://github.com/minad/corfu][Corfu]], [[https://github.com/company-mode/company-mode][Company]] or the default completion UI.

#+begin_src emacs-lisp :tangle init.el
  (use-package cape
    :ensure t
    :defer t
    :commands (cape-dabbrev cape-file cape-elisp-block)
    :bind ("C-c p" . cape-prefix-map)
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block))
#+end_src
** Project management
:PROPERTIES:
:CUSTOM_ID: project-management
:ID:       B5954506-B844-4846-A4D6-0134C726EE1B
:END:
*** Projectile
:PROPERTIES:
:CUSTOM_ID: projectile
:ID:       E8C38F8E-2F20-43C1-BF72-FE14BC6003B3
:END:
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction Library for Emacs.

#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-mode +1)
    )
#+end_src
* Org
:PROPERTIES:
:CUSTOM_ID: org
:ID:       301AFB02-C777-47B8-811F-AB23BAD48BD8
:END:
** Org
:PROPERTIES:
:CUSTOM_ID: org-0
:ID:       E63EFD3D-706E-4EAB-8C44-1F5CB23A89E2
:END:
Why usse Emacs? Because [[https://orgmode.org/][Org-mode]] exists. Org-mode is a  GNU Emacs major mode for
keeping notes, authoring documents, computational notebooks, literate programming,
maintaining to-do lists, planning projects, and more — in a fast and effective
plain text system.

This configuration file is writen with org-mode.

#+begin_src emacs-lisp :tangle init.el
  (use-package org
    :ensure t)
#+end_src

** Org make-toc
:PROPERTIES:
:CUSTOM_ID: org-make-toc
:ID:       B2E0D829-8524-4BB0-8DBF-E1D96A77CF20
:END:
[[https://github.com/alphapapa/org-make-toc][Org-make-toc]] creates tables of contents for org-mode files.

A document may have any number of tables of contents (TOCs), each of which may list entries in a highly
configurable way.

To make a basic TOC, follow these steps:

1. Choose a heading to contain a TOC and move the point to it.
2. Run command =org-make-toc-insert=, which inserts a =:CONTENTS:= drawer and sets TOC properties.
   Set the =include= property to all.
3. Run the command =org-make-toc= to update all TOCs in the document.

Use command =org-make-toc-set= to change TOC properties for the entry at point with completion.

#+begin_src emacs-lisp :tangle init.el
  (use-package org-make-toc
    :ensure t
    :config
    (setq org-make-toc-insert-custom-ids t))

  (defun my/update-toc-before-save-hook ()
    "Update TOC before saving buffer in org-mode"
    (when (eq major-mode 'org-mode)
      (org-make-toc)
      ))

  (add-hook 'before-save-hook #'my/update-toc-before-save-hook)

  (defun my/org-add-ids-to-headlines-in-file ()
    "Add ID properites to all headlines in the current file which do not already have one."
    (interactive)
    (org-map-entries 'org-id-get-create))

  (add-hook 'org-mode-hook
            (lambda () (add-hook 'before-save-hook 'my/org-add-ids-to-headlines-in-file nil 'local)))
#+end_src

** Org reveal
:PROPERTIES:
:ID:       05914648-15E4-40FD-B942-5B41EB7FBFDC
:CUSTOM_ID: org-reveal
:END:
[[https://github.com/yjwen/org-reveal][Org-reveal]] exports your org documents to reaveal.js presentations.

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'load-path "~/.emacs.d/manual-packages/org-reveal/")
  (require 'ox-reveal)
  (setq org-reveal-root "file:///~/.emacs.d/manual-packages/reveal.js/js/reveal.js")
  
#+end_src

*** Htmlize
:PROPERTIES:
:ID:       073835A7-1907-4EB4-806F-D7305D6BE36A
:CUSTOM_ID: htmlize
:END:
[[https://github.com/hniksic/emacs-htmlize][Htmlize]] convert buffer text and decoreations to HTML.

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'load-path "~/.emacs.d/manual-packages/emacs-htmlize/")
  (require 'htmlize)
#+end_src

#+begin_src emacs-lisp :tangle init.el
  (add-to-list 'load-path "~/.emacs.d/manual-packages/org-present/")
  (autoload 'org-present "org-present" nil t)

  (eval-after-load "org-present"
    '(progn
       (add-hook 'org-present-mode-hook
                 (lambda ()
                   (org-present-big)
                   (org-display-inline-images)
                   (org-present-read-only)))
       (add-hook 'org-present-mode-quit-hook
                 (lambda ()
                   (org-present-small)
                   (org-remove-inline-images)
                   (org-present-show-cursor)
                   (org-present-read-write)))))
#+end_src

** Org tempo
:PROPERTIES:
:CUSTOM_ID: org-tempo
:ID:       03CBC294-7BE4-48A8-A742-4DD2D3A9F8BD
:END:
With [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] it is possible to insert empty structural blocks,
such as ‘#+BEGIN_SRC’ … ‘#+END_SRC’, or to wrap existing text in such a block.

|-----+-----------------------------------------|
| Key | Template                                |
|-----+-----------------------------------------|
| c   | ‘#+BEGIN_CENTER’ … ‘#+END_CENTER’       |
| C   | ‘#+BEGIN_COMMENT’ … ‘#+END_COMMENT’     |
| e   | ‘#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE’     |
| a   | ‘#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT’ |
| h   | ‘#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’  |
| l   | ‘#+BEGIN_EXPORT latex’ … ‘#+END_EXPORT’ |
| E   | ‘#+BEGIN_EXPORT’ … ‘#+END_EXPORT’       |
| q   | ‘#+BEGIN_QUOTE’ … ‘#+END_QUOTE’         |
| el  | ‘#+BEGIN_SRC emacs-lisp’ … ‘#+END_SRC’  |
| s   | ‘#+BEGIN_SRC’ … ‘#+END_SRC’             |
| v   | ‘#+BEGIN_VERSE’ … ‘#+END_VERSE’         |
|-----+-----------------------------------------|

#+begin_src emacs-lisp :tangle init.el
  (use-package org-tempo
    :config
    (add-to-list 'org-structure-template-alist
  	       '("el" . "src emacs-lisp")))
#+end_src

** Org bullets
:PROPERTIES:
:CUSTOM_ID: org-bullets
:ID:       15A7A547-A4F5-4B0B-9F9C-023B906799ED
:END:
#+begin_src emacs-lisp :tangle init.el
  (use-package org-bullets
    :ensure t
    )
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src

* Internet
:PROPERTIES:
:CUSTOM_ID: internet
:ID:       B74CB804-F0C5-41A8-92F8-9075E20E0F3E
:END:
** Browse URL
:PROPERTIES:
:CUSTOM_ID: browse-url
:ID:       19A04E3F-27D1-4003-9DA9-1F86BCA9085F
:END:
TODO work in progress

#+begin_src emacs-lisp :tangle init.el
  (use-package browse-url
    :ensure nil
    :custom
    (browse-url-chrome-program "/Application/Google Chrome.app/Contents/MacOS/Google Chrome")
    (browse-url-browser-function 'eww-browse-url)
    :config
    (put 'browse-url-handlers 'safe-local-variable (lambda (x) t))
    (put 'browse-url-browser-function 'safe-local-variable (lambda (x) t)))
#+end_src
** Elfeed
:PROPERTIES:
:CUSTOM_ID: elfeed
:ID:       4D5A1602-9550-4BEF-B09B-6895EC308A63
:END:
[[https://github.com/skeeto/elfeed][An Emacs web feeds client]].
#+begin_src emacs-lisp :tangle init.el
  (use-package elfeed
    :ensure t
    :config
    (setq elfeed-search-feed-face ":foreground #ffffff :weight bold"
          elfeed-feeds (quote
                        (("https://www.reddit.com/r/emacs.rss" reddit emacs)
                         ("https://sachachua.com/blog/category/emacs-news/feed" sacha emacs)
                         ("https://protesilaos.com/codelog.xml" prot emacs)
                         ("https://planet.emacslife.com/atom.xml" planet emacs)
                         ("http://irreal.org/blog/?tag=emacs&feed=rss2" irreal emacs)
                         ("https://taonaw.com/categories/emacs-org-mode/feed.xml" TAONAW emacs)
                         ("https://www.cppstories.com/index.xml" Stories cpp)
                         ("http://feeds.bbci.co.uk/news/world/rss.xml" bbc news)
                         ("https://data.riksdagen.se/dokumentlista/?avd=dokument&doktyp=bet&beslutad=1&sort=beslutsdag&sortorder=desc&utformat=rss" beslut riksdagen)
                         ("https://www.msb.se/sv/rss-floden/rss-alla-nyheter-fran-msb/" news msb)
                         ("https://feeds.feedburner.com/TheHackersNews?format=xml" hacker news)
                         ("https://www.dpreview.com/feeds/news/latest" photography dpreview)
                         ))))
#+end_src
* Shells and terminals
:PROPERTIES:
:CUSTOM_ID: shells-and-terminals
:ID:       64CFFC69-182E-420E-AFA2-74053A7CF939
:END:
** Eshell
:PROPERTIES:
:CUSTOM_ID: eshell
:ID:       26D21080-CD8B-425D-9588-FD4E01D2011D
:END:
Eshell is an Emacs shell written in Elisp.
#+begin_src emacs-lisp :tangle init.el
  (use-package eshell-toggle
    :ensure t
    :custom
    (eshell-toggle-size-fraction 3)
    (ehsell-toggle-use-projectile-root t)
    (eshell-toggle-run-command nil)
    (ehsell-toggle-init-function #'eshell-toggle-init-ansi-term))

  (use-package eshell-syntax-highlighting
    :ensure t
    :after esh-mode
    :config
    (eshell-syntax-highlighting-global-mode +1))

  (setq eshell-rc-script (concat user-emacs-directory "eshell/profile")
        eshell-aliases-file (concat user-emacs-directory "eshell/aliases")
        eshell-history-size 5000
        eshell-buffer-maximum-lines 5000
        eshell-hist-ignoredups t
        eshell-scroll-to-bottom-on-input t
        eshell-destroy-buffer-when-process-dies t
        eshell-visual-commands '("bash" "fish" "htop" "ssh" "top" "zsh"))
#+end_src
