#+TITLE: My literate Emacs Configuration
#+AUTHOR: Marcus

* Emacs Configuration 

=WARNING=

This is my personal Emacs configuration. It is a work in progress. The relavant
configuration files are tangled from this Org-document (=C-c C-v t=). I don't
tangle on save or anything like that. This is a work in progress and will never
be done. This is a rabbit hole...

I regulary commit my configuration to github even though it is not working. Yes,
I know, I shouldn't but I do so you have been warned.

*Here be dragons*

If you are looking for insperation, check out these instead:
- [[https://sachachua.com/blog/][Sacha Chua's Living an awesome life]]
- [[https://protesilaos.com/][Protesilaos Stavrou's personal website]]
- [[https://www.spacemacs.org/][Spacemacs - a community-driven Emacs distribution]]
- [[https://github.com/doomemacs/doomemacs][Doom Emacs - a configuration framework for Emacs]]

If you want to learn more about Org:
- [[https://orgmode.org/manual/index.html][The Org manual]]
- [[https://www.gnu.org/software/emacs/tour/][A guided tour of Emacs]]
- [[https://www.gnu.org/software/emacs/manual/index.html][GNU Emacs Manuals Online]]
  
* Table of Contents
:PROPERTIES:
:TOC:      :include all :depth 4 :force (nothing) :ignore (this) :local (nothing)
:END:
:CONTENTS:
- [[#emacs-configuration][Emacs Configuration]]
- [[#generate-files-and-file-headers][Generate files and file headers]]
  - [[#initel][init.el]]
  - [[#early-initel][early-init.el]]
  - [[#customel][custom.el]]
- [[#package-manager][Package Manager]]
- [[#macos-specifics][MacOS Specifics]]
  - [[#exec-path-from-shell][Exec path from shell]]
  - [[#macos-keyboard-settings][MacOS keyboard settings]]
- [[#look-and-feel][Look and Feel]]
  - [[#misc-settings][Misc settings]]
  - [[#keybindings][Keybindings]]
    - [[#evil][Evil]]
    - [[#my-personal-key-bindings][My personal key bindings]]
    - [[#helpful][Helpful]]
    - [[#move-text][Move text]]
  - [[#minibuffer][Minibuffer]]
    - [[#which-key][Which key]]
    - [[#vertico][Vertico]]
    - [[#save-history][Save history]]
    - [[#marginalia][Marginalia]]
    - [[#orderless][Orderless]]
    - [[#emacs-minibuffer-configurations][Emacs minibuffer configurations]]
  - [[#themes][Themes]]
    - [[#ef-themes][EF-themes]]
    - [[#doom-themes][Doom Themes]]
    - [[#modeline][Modeline]]
    - [[#icons][Icons]]
    - [[#windows][Windows]]
- [[#programming][Programming]]
  - [[#version-control][Version control]]
    - [[#magit][Magit]]
  - [[#project-management][Project management]]
    - [[#projectile][Projectile]]
- [[#org][Org]]
  - [[#org][Org]]
  - [[#org-make-toc][Org make-toc]]
  - [[#org-tempo][Org tempo]]
- [[#internet][Internet]]
  - [[#browse-url][Browse URL]]
:END:

* Generate files and file headers
The file headers sets [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical-binding]] to true. I also try to warn people not to
use this configuration as is.

*Here be dragons*

** init.el
Header text and [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding]].

#+begin_src emacs-lisp :tangle init.el
;;; init.el -*- lexical-binding: t; -*-

;;; Commentary:
;; This is my personal Emacs configuration. The file is tangled from a
;; literate org document where I try to document what each piece is for.
;; If you found my configurations you are free to use as you please, but
;; please read the whole thing before you do. I regulary commit my
;; configuration even though it is not working. Yes, I know, you shouldn't
;; do that but you have been warned.

;; Here be dragons

;; Code:
#+end_src

** early-init.el
Header text and [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Lexical-Binding.html][lexical binding]].

#+begin_src emacs-lisp :tangle early-init.el
;;; early-init.el -*- lexical-binding: t; -*-

;;; Commentary:
;; This is my personal Emacs configuration. The file is tangled from a
;; literate org document where I try to document what each piece is for.
;; If you found my configurations you are free to use as you please, but
;; please read the whole thing before you do. I regulary commit my
;; configuration even though it is not working. Yes, I know, you shouldn't
;; do that but you have been warned.

;; Here be dragons

;; Code:
#+end_src

** custom.el
In Emacs, a custom file is used to store customization settings seperately
from the main init file, allowing for easier management of user preferences.
I use this literate org-file but I like to separate the preferences all the same.

#+begin_src emacs-lisp :tangle init.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))
#+end_src

* Package Manager
[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html][Package installation]] are usually installed using =use-package=. Some packages
are downloaded or cloned from sources outside of the ones listed below. These
packages live in =~/.emacs.d/manual-packages=. This code sets up the package
manager, adds sources and initialize the packages manager.

#+begin_src emacs-lisp :tangle init.el
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
  			 ("melpa-stable" . "https://stable.melpa.org/packages/")
  			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
  			 ("gnu" . "https://elpa.gnu.org/packgages/")))
  (setq package-user-dir (expand-file-name "~/.emacs.d/packages"))
  (require 'package)
  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))
  (package-install-selected-packages)
  (require 'use-package)
#+end_src

* MacOS Specifics
I use a MacBook (arm) for my main laptop. I *try* to keep all the MacOS stuff
behind =when= so I can use this configuration on my Linux machines as well.

** Exec path from shell
A GNU Emacs library to ensure environment variables inside Emacs look the same
as in the user's shell.

#+begin_src emacs-lisp :tangle init.el
(when (memq window-system '(mac ns))
  (use-package exec-path-from-shell
  :ensure t
  :config
  (exec-path-from-shell-initialize)))
#+end_src

** MacOS keyboard settings
My prefered keyboard settings when on a Mac.

#+begin_src emacs-lisp :tangle init.el
(when (eq system-type 'darwin)
  (setq mac-option-modifier 'meta
        mac-command-modifier 'super
        mac-right-option-modifier 'none)
  (global-set-key (kbd "s-c") 'kill-ring-save)
  (global-set-key (kbd "s-v") 'yank)
  (global-set-key (kbd "s-x") 'kill-region)
  (global-set-key (kbd "s-a") 'mark-whole-buffer)
  (global-set-key (kbd "s-z") 'undo)
  (global-set-key (kbd "s-f") 'isearch-forward)
  (global-set-key (kbd "s-g") 'isearch-repeat-forward)
  (global-set-key (kbd "s-o") 'find-file)
  (global-set-key (kbd "s-n") 'find-file)
  (global-set-key (kbd "s-s") 'save-buffer)
  ;(global-set-key (kbd "s-p") 'mac-preview)
  (global-set-key (kbd "s-w") 'kill-buffer)
  (global-set-key (kbd "s-m") 'iconify-frame)
  (global-set-key (kbd "s-q") 'save-buffers-kill-emacs)
  (global-set-key (kbd "s-.") 'keyboard-quit)
  (global-set-key (kbd "s-l") 'goto-line)
  (global-set-key (kbd "s-k") 'kill-buffer)
  (global-set-key (kbd "s-<up>") 'beginning-of-buffer)
  (global-set-key (kbd "s-<down>") 'end-of-buffer)
  (global-set-key (kbd "s-<left>") 'beginning-of-line)
  (global-set-key (kbd "s-<right>") 'end-of-line)
  (global-set-key [(meta down)] 'forward-paragraph)
  (global-set-key [(meta up)] 'backward-paragraph)
  )
#+end_src
* Look and Feel
** Misc settings
Settings that doesn't fit in anywhere else.

#+begin_src emacs-lisp :tangle init.el
  (setq-default c-basic-offset 4
  	      c-default-style "linux"
  	      indent-tabs-mode nil
  	      fill-column 80
  	      tab-width 4)

  (tool-bar-mode -1)                 ; Disable the tool-bar.
  (scroll-bar-mode -1)               ; Specify whether to have vertical scroll bars, and on which side.
  (menu-bar-mode t)                  ; I use a Mac and it looks odd if there is no menu

  (setq load-prefer-newer t)         ; Non-nil means load prefers the newest version of a file.
  (setq tab-always-indent 'complete) ; Controls the operation of the TAB key.
#+end_src
** Keybindings
*** Evil
[[https://github.com/emacs-evil/evil][Evil]] is an extensible *vi* layer for Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package evil
    :ensure t
    :init
    (setq evil-want-integration t
          evil-want-keybinding nil
          evil-vsplit-window-right t
          evil-split-window-below t
          evil-undo-system 'undo-redo)
    (evil-mode 1))
  (use-package evil-collection
    :ensure t
    :after evil
    :config
    (add-to-list 'evil-collection-mode-list 'help)
    (evil-collection-init))
  (with-eval-after-load 'evil-maps
    (define-key evil-motion-state-map (kbd "SPC") nil)
    (define-key evil-motion-state-map (kbd "RET") nil)
    (define-key evil-motion-state-map (kbd "TAB") nil))
  (setq org-return-follows-link t)
#+end_src
*** My personal key bindings
I will try to enter all my personal key bindings here... but some are defined
in the MacOS keyboard settings and some are defined in other places. Oh my.

#+begin_src emacs-lisp :tangle init.el
  (global-set-key (kbd "C-c t") 'ef-themes-toggle)       ; toggle theme 
  (global-set-key (kbd "C-c g") 'magit-status)           ; magit status
  (global-set-key (kbd "C-c p") 'projectile-command-map) ; projectile command map
  (global-set-key (kbd "C-+") 'text-scale-increase)      ; increase text size
  (global-set-key (kbd "C--") 'text-scale-decrease)      ; decrease text size
  (global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
  (global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
#+end_src
*** IVY and Counsel
#+begin_src emacs-lisp :tangle init.el
  (use-package counsel
    :ensure t
    :after ivy
    :diminish
    :config
    (counsel-mode)
    (setq ivy-initial-inputs-alist nil))

  (use-package ivy
    :ensure t
    :bind
    (("C-c C-r" . ivy-resume)
     ("C-x B" . ivy-switch-buffer-other-window))
    :diminish
    :custom
    (setq ivy-use-virtual-buffers t
          ivy-count-format "(%d/%d) "
          enable-recursive-minibuffers t)
    :config
    (ivy-mode))

  (use-package all-the-icons-ivy-rich
    :ensure t
    :init (all-the-icons-ivy-rich-mode 1))

  (use-package ivy-rich
    :ensure t
    :after ivy
    :init (ivy-rich-mode 1)
    :custom (ivy-virtual-abbreviate 'full
                                    ivy-rich-switch-buffer-align-virtual-buffer t
                                    ivy-rich-path-style 'abbrev)
    :config
    (ivy-set-display-transformer 'ivy-switch-buffer
                                 'ivy-rich-switch-buffer-transformer))
#+end_src
*** General key binding
[[https://github.com/noctuid/general.el][General]] is a more convenient key definition system in Emacs.
#+begin_src emacs-lisp :tangle init.el
  (use-package general
    :ensure t
    :config
    (general-evil-setup)
    ;; set up "SPC" as the global leader key
    (general-create-definer my/leader-keys
                            :states '(normal insert visual emacs)
                            :keymaps 'override
                            :prefix "SPC"
                            :global-prefix "M-SPC") ; access leader key in insert mode
    (my/leader-keys
     "SPC" '(counsel-M-x :wk "Counsel M-x")
     "." '(find-file :wk "Find file")
     "TAB TAB" '(comment-line :wk "Comment lines")
     "u" '(universal-argument :wk "Universal argument")
     )

    (my/leader-keys
      "b" '(:ignore t :wk "Bookmarks/Buffers")
      "b b" '(switch-to-buffer :wk "Switch to buffer")
      "b c" '(clone-indirect-buffer :wk "Create indirect buffer copy in a split")
      "b C" '(clone-indirect-buffer-other-window :wk "Clone indirect buffer in new window")
      "b d" '(bookmark-delete :wk "Delete bookmark")
      "b i" '(ibuffer :wk "Ibuffer")
      "b k" '(kill-current-buffer :wk "Kill current buffer")
      "b l" '(list-bookmarks :wk "List bookmarks")
      "b m" '(bookmark-set :wk "Set bookmark")
      "b n" '(next-buffer :wk "Next buffer")
      "b p" '(previous-buffer :wk "Previous buffer")
      "b r" '(revert-buffer :wk "Reload buffer")
      "b R" '(rename-buffer :wk "Rename buffer")
      "b s" '(basic-save-buffer :wk "Save buffer")
      "b S" '(save-some-buffers :wk "Save multiple buffers")
      "b w" '(bookmark-save :wk "Save current bookmarks to bookmark file")
      )

    (my/leader-keys
      "d" '(:ignore t :wk "Dired")
      "d d" '(dired :wk "Open dired")
      "d j" '(dired-jump :wk "Dired jump to current")
      )

    (my/leader-keys
      "e" '(:ignore t :wk "Eshell/Evaluate")
      "e b" '(eval-buffer :wk "Evaluate elisp in buffer")
      "e d" '(eval-defun :wk "Evaluate defun containing or after point")
      "e e" '(eval-expression :wk "Evaluate and elisp expression")
      "e h" '(counsel-ssh-history :wk "Eshell history")
      "e l" '(eval-last-sexp :wk "Evaluate elisp expression before point")
      "e r" '(eval-region :wk "Evaluate elisp in region")
      "e R" '(eww-reload :wk "Reload current page in EWW")
      "e s" '(eshell :wk "Eshell")
      "e w" '(eww :wk "EWW emacs web browser")
      )

    (my/leader-keys
      "f" '(:ignore t :wk "Files")
      "f c" '((lambda () (interactive) (find-file "~/.emacs.d/README.org")) :wk "Open emacs configuration file")
      "f e" '((lambda () (interactive) (dired "~/.emacs.d/")) :wk "Open user-emacs-directory in dired")
      "f g" '(counsel-grep-or-swiper :wk "Search for string current file")
      "f j" '(counsel-file-jump :wk "Jump to a file below current directory")
      "f l" '(counsel-locate :wk "Locate a file")
      "f r" '(counsel-recentf :wk "Find recent files")
      )

    (my/leader-keys
      "g" '(:ignore t :wk "Git")
      "g d" '(magit-dispatch :wk "Magit dispatch")
      "g ." '(magit-file-dispatch :wk "Magit file dispatch")
      "g b" '(magit-branch-checkout :wk "Switch branch")
      "g c" '(:ignore t :wk "Create")
      "g c b" '(magit-branch-and-checkout :wk "Create branch and checkout")
      "g c c" '(magit-commit-create :wk "Create commit")
      "g c f" '(magit-commit-fixup :wk "Create fixup commit")
      "g C" '(magit-clone :wk "Clone repo")
      "g f" '(:ignore t :wk "Find")
      "g f c" '(magit-show-commit :wk "Magit show commit")
      "g f f" '(magit-find-file :wk "Magit find file")
      "g f g" '(magit-find-git-config-file :wk "Find gitconfig file")
      "g F" '(magit-fetch :wk "Git fetch")
      "g g" '(magit-status :wk "Magit status")
      "g i" '(magit-init :wk "Initialize git repo")
      "g l" '(magit-log-buffer-file :wk "Magit buffer log")
      "g r" '(vc-revert :wk "Git revert file")
      "g s" '(magit-stage-file :wk "Git stage file")
      "g u" '(magit-unstage-file :wk "Git unstage file")
      )
    ) 
#+end_src
*** Helpful
[[https://github.com/Wilfred/helpful][Helpful]] is an alternative to the built-in Emacs help that provides much more contextual information.

#+begin_src emacs-lisp :tangle init.el
  (use-package helpful
    :ensure t
    :commands (helpful-at-point
  	     helpful-callable
  	     helpful-command
  	     helpful-function
  	     helpful-key
  	     helpful-macro
  	     helpful-variable)
    :bind
    ([remap display-local-help] . helpful-at-point)
    ([remap describe-function] . helpful-callable)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-symbol] . helpful-symbol)
    ([remap describe-key] . helpful-key)
    ([remap describe-command] . helpful-command))
#+end_src
*** Move text
[[https://github.com/emacsfodder/move-text][MoveText]] allows you to move the current line using M-up / M-down (or any other bindings you choose)
if a region is marked, it will move the region instead.

#+begin_src emacs-lisp :tangle init.el
  (use-package move-text
    :ensure t
    :defer
    :init (move-text-default-bindings))
#+end_src
** Minibuffer
*** Which key
[[https://github.com/justbur/emacs-which-key][which-key]] is a minor mode for Emacs that displays the key bindings following your currently entered incomplete
command (a prefix) in a popup. 

#+begin_src emacs-lisp :tangle init.el
  (use-package which-key
    :ensure t
    :delight
    :custom (which-key-idle-delay 0.5)
    :config (which-key-mode))
#+end_src
*** Vertico
[[https://github.com/minad/vertico][Vertico]] provides a performant and minimalistic vertical completion UI based on the default completion system. 

#+begin_src emacs-lisp :tangle init.el
    (use-package vertico
      :ensure t
      :init (vertico-mode)
      :bind (:map vertico-map
    	      ("C-<backspace>" . vertico-directory-up))
      :config
      (keymap-set vertico-map "?" #'minibuffer-completion-help)
      (keymap-set vertico-map "M-RET" #'minibuffer-force-complete-and-exit)
      (keymap-set vertico-map "M-TAB" #'minibuffer-complete))
#+end_src
*** Save history
Vertico sorts by history position.

#+begin_src emacs-lisp :tangle init.el
  (use-package savehist
    :init
    (savehist-mode))
#+end_src
*** Marginalia
[[https://github.com/minad/marginalia][Marginalia]] are marks or annotations placed at the margin of the page of a book or in this case helpful colorful
annotations placed at the margin of the minibuffer for your completion candidates.

#+begin_src emacs-lisp :tangle init.el
  (use-package marginalia
    :ensure t
    :after vertico
    :init (marginalia-mode)
    :custom
    (marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light nil)))
#+end_src
*** Orderless
This package provides an [[https://github.com/oantolin/orderless][orderless]] completion style that divides the pattern into space-separated components,
and matches candidates that match all of the components in any order. Each component can match in any one of several
ways: literally, as a regexp, as an initialism, in the flex style, or as multiple word prefixes. By default, regexp
and literal matches are enabled.

#+begin_src emacs-lisp :tangle init.el
  (use-package orderless
    :ensure t
    :custom
    (completion-category-defaults nil)
    (completion-category-overrides '((file (styles . (partial-completion)))))
    (completion-styles '(orderless)))
#+end_src
*** Emacs minibuffer configurations

#+begin_src emacs-lisp :tangle init.el
  (use-package emacs
    :custom
    (enable-recursive-minibuffers t)
    (read-extended-command-predicate #'command-completion-default-include-p)
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))
#+end_src
** Themes and Fonts
Some packages, such as EF-themes, I download myself into =~/.emacs.d/manual-packages/<package>=.
To be able to use these packages I first add the path to the =load-path= list and then =require=
each package.

My default theme is =ef-elea-light= and =ef-elea-dark=.
I can switch between these themes using =M-x ef-themes-toggle= or with keybinding =X=.

*** EF-themes
The [[https://github.com/protesilaos/ef-themes][ef-themes]] are a collection of light and dark themes for GNU Emacs whose
goal is to provide colorful ("pretty") yet legible options for users who want
something with a bit more flair than the [[https://github.com/protesilaos/modus-themes][modus-themes]].

#+begin_src emacs-lisp :tangle init.el
      (add-to-list 'load-path "~/.emacs.d/manual-packages/ef-themes")
      (require 'ef-themes)
      (setq ef-themes-to-toggle '(ef-arbutus ef-elea-dark))
      (setq ef-themes-headings
      	'((0 variable-pitch light 1.9)
      	  (1 variable-pitch light 1.8)
      	  (2 variable-pitch regular 1.7)
      	  (3 variable-pitch regular 1.6)
      	  (4 variable-pitch regular 1.5)
      	  (5 variable-pitch 1.4) ; absence of weight means 'bold'
      	  (6 variable-pitch 1.3)
      	  (7 variable-pitch 1.2)
      	  (t variable-pitch 1.1)))
    (setq ef-themes-mixed-fonts t
          ef-themes-variable-pitch-ui t)
  (mapc #'disable-theme custom-enabled-themes) ; disable all other themes to avoid awkward blending
  (load-theme 'ef-arbutus :no-confirm)
#+end_src
*** Doom Themes
A [[https://github.com/doomemacs/themes][theme megapack]] for GNU Emacs, inspired by community favorites.

#+begin_src emacs-lisp :tangle init.el
  (use-package doom-themes
    :ensure t)
#+end_src

*** Modeline
[[https://github.com/seagle0128/doom-modeline][Doom modeline]] is used to cleanup and configure the modeline.

#+begin_src emacs-lisp :tangle init.el
  (use-package doom-modeline
    :ensure t
    :config
    (setq
     doom-modeline-support-imenu t
     doom-modeline-icon t
     doom-modeline-major-mode-icon t
     doom-modeline-buffer-state-icon t
     doom-modeline-buffer-modification-icon t
     doom-modeline-column-zero-based t
     doom-modeline-highlight-modified-buffer-name nil
     doom-modeline-percent-position '(-3 "%p")
     doom-modeline-position-column-line-format '("%l:%c")
     doom-modeline-total-line-number t
     doom-modeline-modal t
     doom-modeline-modal-modern-icon t
     doom-modeline-time t
     )
    (setq doom-modeline-height 25)
    (if (facep 'mode-line-active)
        (set-face-attribute 'mode-line-active nil :family "Noto Sans" :height 140)
      (set-face-attribute 'mode-line nil :family "Noto Sans" :height 140)
      (set-face-attribute 'mode-line-inactive nil :family "Noto Sans" :height 140))
    :init
    (doom-modeline-mode 1))
#+end_src

*** Fonts
Setting the font faces.
#+begin_src emacs-lisp :tangle init.el
  (set-face-attribute 'default nil
                      :font "Iosevka Fixed"
                      :height 160
                      :weight 'medium)
  (set-face-attribute 'variable-pitch nil
                      :font "Iosevka"
                      :height 150
                      :weight 'medium)
  (set-face-attribute 'fixed-pitch nil
                      :font "Iosevka Fixed"
                      :height 160
                      :weight 'medium)
  (set-face-attribute 'font-lock-comment-face nil
                      :slant 'italic)
  (set-face-attribute 'font-lock-keyword-face nil
                      :slant 'italic)
#+end_src

*** Icons
**** All-the-icons
[[https://github.com/domtronn/all-the-icons.el][All-the-icons]] is a utility package to collect various Icon Fonts and propertize them within Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package all-the-icons
    :ensure t
    :if (display-graphic-p))
#+end_src
**** All-the-icons-completion
[[https://github.com/iyefrat/all-the-icons-completion][All-the-icons-completion]] adds icons to completion candidates in Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package all-the-icons-completion
    :ensure t
    :defer
    :hook (marginalia-mode . #'all-the-icons-completion-marginalia-setup)
    :init
    (all-the-icons-completion-mode))
#+end_src
**** Nerd icons
[[https://github.com/emacsmirror/nerd-icons][Nerd-icons]] - Emacs Nerd Font Icons Library.

#+begin_src emacs-lisp :tangle init.el
  (use-package nerd-icons
    :ensure t)
#+end_src
*** Windows
**** Window
Setup how to split windows in Emacs.

#+begin_src emacs-lisp :tangle init.el
  (use-package window
    :ensure nil
    :bind (("C-x 2" . vsplit-last-buffer)
           ("C-x 3" . hsplit-last-buffer)
           ([remap kill-buffer] . kill-this-buffer))
    :preface
    (defun hsplit-last-buffer ()
      "Focus to the last created horizontal window."
      (interactive)
      (split-window-horizontally)
      (other-window 1))
    (defun vsplit-last-buffer ()
      "Focus to the last created vertical window."
      (interactive)
      (split-window-vertically)
      (other-window 1)))
#+end_src
**** Switch window
[[https://github.com/dimitri/switch-window][Switch-window]] offer a visual way to choose a window to switch to.

#+begin_src emacs-lisp :tangle init.el
  (use-package switch-window
    :ensure t
    :bind (("C-x o" . switch-window)
           ("C-x w" . switch-window-then-swap-buffer)))
#+end_src
**** Winner
Winner mode in Emacs allows you to restore previous window configurations after
they have been changed, making it easier to manage your layout.

#+begin_src emacs-lisp :tangle init.el
  (use-package winner
    :ensure nil
    :config (winner-mode))
#+end_src
**** Ibuffer
I found a post [[https://tech.tonyballantyne.com/2020/09/26/ibuffer-changed-my-life/][ibuffer changed my life]] from Tony Ballantyne Tech.

#+begin_src emacs-lisp :tangle init.el
  (global-set-key (kbd "C-x C-b") 'ibuffer) ; instead of buffer-list
  (setq ibuffer-expert t)                   ; stop yes no prompt on delete
  (setq ibuffer-saved-filter-groups
        (quote (("default"
                 ("dired" (mode . dired-mode))
                 ("org" (mode . org-mode))
                 ("magit" (name . "^magit"))
                 ("planner" (or
                             (name . "^\\*Calendar\\*$")
                             (name . "^\\*Org Agenda\\*$")))
                 ("emacs" (or
                           (name . "^\\*scratch\\*$")
                           (name . "^\\*Messages\\*$")))
                 ))))
  (add-hook 'ibuffer-mode-hook (lambda ()
                                 (ibuffer-switch-to-saved-filter-groups "default")))
#+end_src
**** Dashboard
[[https://github.com/emacs-dashboard/emacs-dashboard][Dashboard]] is an extensible emacs startup screen showing you what’s most important.

#+begin_src emacs-lisp :tangle init.el
  (use-package dashboard
    :ensure t
    :config
    (setq dashboard-banner-logo-text "Emacs, what else?"
          dashboard-startup-banner 'official
          dashboard-center-content t
          dashboard-vertically-center-content t
          dashboard-show-shortcuts t)
    (setq dashboard-items '((recents . 10)
                            (bookmarks . 10)
                            (projects . 10)
                            (agenda . 10)
                            (registers . 10)))
    (setq dashboard-item-shortcuts '((recents . "r")
                                     (bookmarks . "b")
                                     (projects . "p")
                                     (agenda . "a")
                                     (registers . "e")))
    (setq dashboard-navigation-cycle t
          dashboard-display-icons-p t)
          ;dashboard-icon-type 'nerd-icons
          ;dashboard-set-heading-icons t
          ;dashboard-set-file-icons t
          ;dashboard-icon-file-height 1.75
          ;dashboard-icon-file-v-adjust -0.125
          ;dashboard-heading-icon-height 1.75
          ;dashboard-heading-icon-v-adjust -0.125)
    :init
    (dashboard-setup-startup-hook))
#+end_src
* Programming
** Version control
*** Magit
[[https://magit.vc/][Magit]] is a complete text-based user interface to Git. It fills the glaring gap between
the Git command-line interface and various GUIs, letting you perform trivial as well as
elaborate version control tasks with just a couple of mnemonic key presses. Magit looks
like a prettified version of what you get after running a few Git commands but in Magit
every bit of visible information is also actionable to an extent that goes far beyond
what any Git GUI provides and it takes care of automatically refreshing this output when
it becomes outdated. In the background Magit just runs Git commands and if you wish you
can see what exactly is being run, making it possible for you to learn the git command-line
by using Magit.


#+begin_src emacs-lisp :tangle init.el
  (use-package magit
    :ensure t)
#+end_src
** Project management
*** Projectile
[[https://github.com/bbatsov/projectile][Projectile]] is a project interaction Library for Emacs.

#+begin_src emacs-lisp
  (use-package projectile
    :ensure t
    :init
    (projectile-mode +1)
    )
#+end_src
* Org
** Org                                                              
Why usse Emacs? Because [[https://orgmode.org/][Org-mode]] exists. Org-mode is a  GNU Emacs major mode for
keeping notes, authoring documents, computational notebooks, literate programming,
maintaining to-do lists, planning projects, and more — in a fast and effective
plain text system.

This configuration file is writen with org-mode.

#+begin_src emacs-lisp :tangle init.el
  (use-package org
    :ensure t)
#+end_src

** Org make-toc
[[https://github.com/alphapapa/org-make-toc][Org-make-toc]] creates tables of contents for org-mode files.

A document may have any number of tables of contents (TOCs), each of which may list entries in a highly
configurable way.

To make a basic TOC, follow these steps:

1. Choose a heading to contain a TOC and move the point to it.
2. Run command =org-make-toc-insert=, which inserts a =:CONTENTS:= drawer and sets TOC properties.
   Set the =include= property to all.
3. Run the command =org-make-toc= to update all TOCs in the document.

Use command =org-make-toc-set= to change TOC properties for the entry at point with completion.

#+begin_src emacs-lisp :tangle init.el
  (use-package org-make-toc
    :ensure t)
#+end_src

** Org tempo
With [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] it is possible to insert empty structural blocks,
such as ‘#+BEGIN_SRC’ … ‘#+END_SRC’, or to wrap existing text in such a block.

|-----+-----------------------------------------|
| Key | Template                                |
|-----+-----------------------------------------|
| c   | ‘#+BEGIN_CENTER’ … ‘#+END_CENTER’       |
| C   | ‘#+BEGIN_COMMENT’ … ‘#+END_COMMENT’     |
| e   | ‘#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE’     |
| a   | ‘#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT’ |
| h   | ‘#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’  |
| l   | ‘#+BEGIN_EXPORT latex’ … ‘#+END_EXPORT’ |
| E   | ‘#+BEGIN_EXPORT’ … ‘#+END_EXPORT’       |
| q   | ‘#+BEGIN_QUOTE’ … ‘#+END_QUOTE’         |
| el  | ‘#+BEGIN_SRC emacs-lisp’ … ‘#+END_SRC’  |
| s   | ‘#+BEGIN_SRC’ … ‘#+END_SRC’             |
| v   | ‘#+BEGIN_VERSE’ … ‘#+END_VERSE’         |
|-----+-----------------------------------------|

#+begin_src emacs-lisp :tangle init.el
  (use-package org-tempo
    :config
    (add-to-list 'org-structure-template-alist
  	       '("el" . "src emacs-lisp")))
#+end_src
* Internet
** Browse URL
TODO work in progress

#+begin_src emacs-lisp :tangle init.el
  (use-package browse-url
    :ensure nil
    :custom
    (browse-url-chrome-program "/Application/Google Chrome.app/Contents/MacOS/Google Chrome")
    (browse-url-browser-function 'eww-browse-url)
    :config
    (put 'browse-url-handlers 'safe-local-variable (lambda (x) t))
    (put 'browse-url-browser-function 'safe-local-variable (lambda (x) t)))
#+end_src
** Elfeed
[[https://github.com/skeeto/elfeed][An Emacs web feeds client]].
#+begin_src emacs-lisp :tangle init.el
  (use-package elfeed
    :ensure t
    :config
    (setq elfeed-search-feed-face ":foreground #ffffff :weight bold"
          elfeed-feeds (quote
                        (("https://www.reddit.com/r/emacs.rss" reddit emacs)
                         ("https://sachachua.com/blog/category/emacs-news/feed" sacha emacs)
                         ))))
#+end_src
